# Basic Information 
title: Haoran Xu
position: Ph.D. Student
affiliation: Electrical and Computer Engineering, University of Michigan
email: haoranxu (at) umich.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Haoran Xu, University of Michigan, UMich ECE, PhD, energy storage systems, battery management systems, sustainable transportation, AI for debugging
description: Haoran Xu is an incoming Ph.D. student in Electrical and Computer Engineering at the University of Michigan, advised by Prof. Ziyou Song.
canonical: https://xuhr22.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=VO0Dk4MAAAAJ&hl=en
cv_link: assets/files/CV-Haoran-Xu.pdf
github_link: https://github.com/xuhr22
linkedin: https://www.linkedin.com/in/haoran-xu-a1b7b3386/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/4.JPG
favicon: ./assets/img/4.JPG
favicon_dark: ./assets/img/4.JPG

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
